package:
  name: classix
  version: 0.0.8

source:
  fn: ClassixClustering-0.3.3.tar.gz
  url: https://files.pythonhosted.org/packages/b5/ca/615f0cec2694057692989204bf5be01187257a0c382a569d5e1df1cb65b7/ClassixClustering-0.3.3.tar.gz
  sha256: b914b701ff55223f6913b7c7ed99a9daa4e1bd5476fd26c88db7e68186563ba2

requirements:
  host:
    - python
    - pandas
    - numpy >=1.20.0
    - setuptools
    - cython
    - scipy
    - matplotlib

  build:
    - pip
    - python
    - pandas
    - numpy >=1.20.0
    - setuptools
    - cython
    - scipy
    - matplotlib

  run:
    - python

about:
  home: https://github.com/nla-group/classix
  license_family: MIT
  license_file: LICENSE
