package:
  name: classix
  version: 0.0.2

source:
  fn: ClassixClustering-0.1.9.tar.gz
  url: https://files.pythonhosted.org/packages/f5/cf/b390f8dc4dfecf10a24234286fa5efc587c9cc3734fa36be844ed6daafec/ClassixClustering-0.1.9.tar.gz
  sha256: 41b2552027327d8414c6874a386dfc6a2c5a490f31ae4fa2bbd44a618a78d1a2

requirements:
  build:
    - python
    - pandas
    - numpy>=1.20.0
    - setuptools
    - cython
    - scipy
    - matplotlib

  run:
    - python

about:
  home: https://github.com/nla-group/classix
  license_family: MIT
  license_file: LICENSE