package:
  name: classix
  version: 0.0.8

source:
  fn: ClassixClustering-0.3.4.tar.gz
  url: https://files.pythonhosted.org/packages/04/b1/c6dda9bde56d492d664bc0e00fac050108e174417137b88dd694f9b04b36/ClassixClustering-0.3.4.tar.gz
  sha256: 854d4277e1f62f5d8a30ebb6e61cba248d637ed5f5b73b9b7b4aea17efe6006d

requirements:
  host:
    - python
    - pandas
    - numpy >=1.20.0
    - setuptools
    - cython
    - scipy
    - matplotlib

  build:
    - pip
    - python
    - pandas
    - numpy >=1.20.0
    - setuptools
    - cython
    - scipy
    - matplotlib

  run:
    - python

about:
  home: https://github.com/nla-group/classix
  license_family: MIT
  license_file: LICENSE
