package:
  name: classix
  version: 0.0.6

source:
  fn: ClassixClustering-0.3.0.tar.gz
  url: https://files.pythonhosted.org/packages/09/23/57163137e9ba94c602c3ede86d6ed7f95ef88ee9d186f841eb68d8eb62f7/ClassixClustering-0.3.0.tar.gz
  sha256: 316ac54d68a444dfe6b664a048b6988a11b6f6b782377f74c8f57683140381a8

requirements:
  host:
    - python
    - pandas
    - numpy >=1.20.0
    - setuptools
    - cython
    - scipy
    - matplotlib

  build:
    - pip
    - python
    - pandas
    - numpy >=1.20.0
    - setuptools
    - cython
    - scipy
    - matplotlib

  run:
    - python

about:
  home: https://github.com/nla-group/classix
  license_family: MIT
  license_file: LICENSE
