package:
  name: classix
  version: 0.0.3

source:
  fn: ClassixClustering-0.2.7.tar.gz
  url: https://files.pythonhosted.org/packages/f5/e6/aa65b6bc0f73782af2aa72ab2bb7415010499c512750174bc69ae2366bf2/ClassixClustering-0.2.7.tar.gz
  sha256: 3de629f1a8a034cce216ac018e7b947227815b282ad4a9f9102071ab4dfedc65

requirements:
  host:
    - python
    - pandas
    - numpy >=1.20.0
    - setuptools
    - cython
    - scipy
    - matplotlib

  build:
    - python
    - pandas
    - numpy >=1.20.0
    - setuptools
    - cython
    - scipy
    - matplotlib

  run:
    - python

about:
  home: https://github.com/nla-group/classix
  license_family: MIT
  license_file: LICENSE
