package:
  name: classix
  version: 0.0.6

source:
  fn: ClassixClustering-0.3.2.tar.gz
  url: https://files.pythonhosted.org/packages/66/d8/695f8af954fefd48cc31c8764f8db8c8d9ff2ffd609e39409a186e9a80e6/ClassixClustering-0.3.2.tar.gz
  sha256: 2ccad8067b49b942f0720abd8d049682df213686e11768e80fef979fda506504

requirements:
  host:
    - python
    - pandas
    - numpy >=1.20.0
    - setuptools
    - cython
    - scipy
    - matplotlib

  build:
    - pip
    - python
    - pandas
    - numpy >=1.20.0
    - setuptools
    - cython
    - scipy
    - matplotlib

  run:
    - python

about:
  home: https://github.com/nla-group/classix
  license_family: MIT
  license_file: LICENSE
