package:
  name: classix
  version: 0.0.9

source:
  fn: ClassixClustering-0.3.5.tar.gz
  url: https://files.pythonhosted.org/packages/04/55/ba245962599b1f9e35af276e3584be4e2d39b1ab9f61505170f594bfe746/ClassixClustering-0.3.5.tar.gz
  sha256: fdb5234ea2ad62d8dae0f23a339498682a3b907121c437be8c453c6bb06371d5

requirements:
  host:
    - python
    - pandas
    - numpy >=1.20.0
    - setuptools
    - cython
    - scipy
    - matplotlib

  build:
    - pip
    - python
    - pandas
    - numpy >=1.20.0
    - setuptools
    - cython
    - scipy
    - matplotlib

  run:
    - python

about:
  home: https://github.com/nla-group/classix
  license_family: MIT
  license_file: LICENSE
